'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowLeft } from 'lucide-react'
import { erpFetch } from '@/lib/erp-api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

type DispatchOrder = {
  id: string
  do_number?: string | null
  sales_order_id: string
  sales_order_number?: string | null
  customer_name?: string | null
  status: 'awaiting_invoice' | 'awaiting_approval' | 'dispatched'
  generated_by_name?: string | null
  created_at: string
  dispatch_order_lines?: Array<{ id: string; item_sku?: string | null; item_name?: string | null; qty_to_dispatch?: number | null }>
}

function statusLabel(status: string): string {
  return status
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

export default function InvoiceRequestsPage() {
  const router = useRouter()
  const [rows, setRows] = useState<DispatchOrder[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    void (async () => {
      setLoading(true)
      setError(null)
      try {
        const res = await erpFetch<{ data: DispatchOrder[] }>('/api/dispatch/orders?status=awaiting_invoice')
        setRows(res.data ?? [])
      } catch (e) {
        setError(e instanceof Error ? e.message : 'Failed to load invoice requests')
      } finally {
        setLoading(false)
      }
    })()
  }, [])

  return (
    <div className="p-6 md:p-8 space-y-6">
      <Button asChild variant="ghost" className="pl-0">
        <Link href="/dashboard/finance">
          <ArrowLeft className="size-4 mr-2" /> Back to Accounts
        </Link>
      </Button>

      <Card>
        <CardHeader>
          <CardTitle>Invoice Requests</CardTitle>
          <CardDescription>Dispatch orders awaiting invoice generation.</CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? <p className="text-sm text-muted-foreground">Loading...</p> : null}
          {error ? <p className="text-sm text-red-600">{error}</p> : null}
          {!loading && !error && rows.length === 0 ? (
            <p className="text-sm text-muted-foreground">No invoice requests found.</p>
          ) : null}
          {rows.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left border-b">
                    <th className="py-2 pr-3">Dispatch Order</th>
                    <th className="py-2 pr-3">Sales Order</th>
                    <th className="py-2 pr-3">Customer</th>
                    <th className="py-2 pr-3">Items</th>
                    <th className="py-2 pr-3">Generated By</th>
                    <th className="py-2 pr-3">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row) => (
                    <tr
                      key={row.id}
                      className="border-b cursor-pointer hover:bg-muted/40"
                      onClick={() => router.push(`/dashboard/finance/invoice-requests/${row.id}`)}
                    >
                      <td className="py-2 pr-3 font-mono">{row.do_number ?? row.id.slice(0, 8)}</td>
                      <td className="py-2 pr-3">
                        <Link
                          className="hover:underline"
                          href={`/dashboard/sales/${row.sales_order_id}`}
                          onClick={(e) => e.stopPropagation()}
                        >
                          {row.sales_order_number ?? row.sales_order_id.slice(0, 8)}
                        </Link>
                      </td>
                      <td className="py-2 pr-3">{row.customer_name ?? '-'}</td>
                      <td className="py-2 pr-3">{(row.dispatch_order_lines ?? []).length}</td>
                      <td className="py-2 pr-3">{row.generated_by_name ?? '-'}</td>
                      <td className="py-2 pr-3">{statusLabel(row.status)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : null}
        </CardContent>
      </Card>
    </div>
  )
}
